let nombreDeSuperHeroe = 'Batman';
let nombre = 'Bruce Wayne';
let vuela = 'no';
let maneja = 'si';
let vida = 100;
let trabajo = undefined;
let tiempoLibre = null;
console.log(nombreDeSuperHeroe, 'Batman');
console.log(nombre, 'Bruce Wayne');
console.log(vuela, 'no');
console.log(maneja, 'si');
console.log(vida, 100);
console.log(trabajo, undefined);
console.log(tiempoLibre, null);
console.log(nombreDeSuperHeroe, typeof nombreDeSuperHeroe);
console.log(nombre, typeof nombre);
console.log(vuela, typeof vuela);
console.log(maneja, typeof maneja);
console.log(vida, typeof vida);
console.log(trabajo, typeof trabajo);
console.log(tiempoLibre, typeof tiempoLibre);